import Foundation

enum AppLanguage: String, CaseIterable, Codable {
    case tr
    case en

    var displayCode: String {
        rawValue.uppercased()
    }

    init(code: String) {
        switch code.lowercased() {
        case "en":
            self = .en
        default:
            self = .tr
        }
    }
}

enum AppLocalization {
    static func text(
        _ key: String,
        language: AppLanguage,
        replacements: [String: String] = [:]
    ) -> String {
        var value = translations[language]?[key] ?? translations[.tr]?[key] ?? key
        for (name, replacement) in replacements {
            value = value
                .replacingOccurrences(of: "{\(name)}", with: replacement)
                .replacingOccurrences(of: "{\(name):.0f}", with: replacement)
        }
        return value
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .tr: [
            "status.ok": "Tamam",
            "status.error": "Hata",
            "data.loading": "İstasyonlar hazırlanıyor",
            "data.refresh": "Tekrar dene",
            "data.ready": "{count} istasyon hazır",
            "auth.hero_line1": "Akımı",
            "auth.hero_line2": "yakala.",
            "auth.card_title": "Hesabınla devam et",
            "auth.card_hint": "Favoriler ve bildirimler hesabına kaydedilir.",
            "auth.login": "Giriş",
            "auth.register": "Kayıt",
            "auth.reset": "Sıfırla",
            "auth.mode_label": "Hesap işlemi",
            "auth.continue": "Devam et",
            "auth.email": "E-posta",
            "auth.email_placeholder": "sen@ornek.com",
            "auth.password": "Şifre",
            "auth.password_placeholder": "Şifren",
            "auth.login_action": "Giriş yap",
            "auth.register_action": "Kaydol",
            "auth.reset_action": "Sıfırlama Bağlantısı Gönder",
            "auth.login_loading": "Giriş yapılıyor...",
            "auth.register_loading": "Hesap oluşturuluyor...",
            "auth.reset_loading": "Bağlantı hazırlanıyor...",
            "auth.forgot_password": "Şifremi unuttum",
            "auth.back_to_login": "Girişe dön",
            "auth.reset_hint": "E-postanı yaz, sıfırlama bağlantısını gönderelim.",
            "auth.reset_email_required": "Sıfırlama için e-posta adresini yaz.",
            "auth.fill_fields": "E-posta ve şifre alanlarını doldur.",
            "auth.guest_primary_title": "En yakın şarjı hemen bul",
            "auth.guest_primary_hint": "Üyelik gerekmez. Konumunu seçip rotanı oluşturabilirsin.",
            "auth.guest_primary_action": "Hemen başla",
            "auth.verified_driver": "Doğrulanmış sürücü",
            "auth.signed_in_hint": "Favoriler ve durum bildirimleri bu hesapla senkronize edilir.",
            "auth.logout": "Çıkış yap",
            "auth.firebase_config_required": "Firebase ayarları için AppConfig.plist eklenmeli.",
            "bottom.home": "Ana Sayfa",
            "bottom.map": "Salon",
            "bottom.routes": "Rotalar",
            "bottom.account": "Hesap",
            "nav.back": "Geri",
            "home.quick_near": "Yakın",
            "home.quick_fast": "Hızlı",
            "home.quick_value": "Uygun",
            "home.search_title": "Nereden başlıyorsun?",
            "home.location_selected": "Konum seçilmedi",
            "home.use_location": "Konumumu kullan",
            "home.location_waiting_authorized": "Konum alınıyor. Sinyal gelmezse şehir veya koordinat girişi açılır.",
            "home.location_waiting_pending": "Konum izni bekleniyor. İzin vermezsen şehir veya koordinat girişi açılır.",
            "home.location_waiting_failed": "Konuma erişilemiyor. Şehir veya koordinatla devam edebilirsin.",
            "home.location_pick": "Şehir veya bölge seç",
            "home.latitude": "Enlem",
            "home.longitude": "Boylam",
            "home.use_manual_location": "Manuel konumu kullan",
            "catalog.kicker": "Sürüş profili",
            "catalog.charge_percent": "Şarj %",
            "catalog.capacity": "Batarya kapasitesi",
            "catalog.consumption": "Ortalama tüketim",
            "charge.low": "Düşük",
            "charge.ready": "Yola hazır",
            "charge.long_range": "Uzun menzil",
            "charge.label": "Şarj",
            "charge.selected_level": "Seçili batarya seviyesi",
            "filters.title": "Filtreler ve sürüş ayarları",
            "filters.preference": "Öncelik",
            "filters.power": "Güç",
            "filters.minimum_power": "Minimum {power} kW",
            "filters.socket": "Soket",
            "filters.range": "Menzil dışını gizle",
            "filters.apply": "Uygula",
            "home.insight_kicker": "Akıllı menzil önerisi",
            "home.insight_title": "{range} km güvenli menzille yola hazırsın",
            "summary.safe_range_value": "%{percent} · {range} km güvenli menzil",
            "location.find_charger": "En Uygun İstasyonu Bul",
            "location.calculating": "Hesaplanıyor...",
            "service.firebase_missing": "Firebase ayarları AppConfig.plist içinde tanımlı değil.",
            "service.reset_sent": "Şifre sıfırlama bağlantısı gönderildi.",
            "service.favorite_login_required": "Kaydetmek için giriş yapmalısın.",
            "service.report_login_required": "Durum bildirmek için giriş yapmalısın.",
            "service.no_session": "Oturum yok.",
            "route.location_required": "Rota için konum seçmelisin.",
            "route.idle": "Rota hazır değil",
            "route.idle_hint": "Ana sayfadan konumunu seçip En Uygun İstasyonu Bul'a bas.",
            "route.searching": "En iyi duraklar hesaplanıyor",
            "route.failed": "Rota hesaplanamadı",
            "route.empty": "Uygun istasyon bulunamadı",
            "route.empty_hint": "Filtreleri gevşetip tekrar deneyebilirsin.",
            "route.back_home": "Ana Sayfaya Dön",
            "feed.score": "SKOR",
            "feed.route_approximate": "YAKLAŞIK ROTA",
            "feed.minute": "dk",
            "feed.arrival": "varış",
            "feed.arrival_charge": "Varış şarjı",
            "feed.deviation": "Sapma",
            "feed.power": "GÜÇ",
            "feed.socket": "SOKET",
            "feed.price": "FİYAT",
            "feed.detail_card": "ŞARJ NOKTASI",
            "feed.open_route": "Rotayı Aç",
            "feed.apple_maps": "Apple Maps",
            "feed.google_maps": "Google Maps",
            "feed.open_in_maps": "Rotayı Haritalar'da aç",
            "feed.favorite_add": "Favoriye ekle",
            "feed.favorite_remove": "Favoriden çıkar",
            "actions.available": "Uygun",
            "actions.issue_value": "Sorun var",
            "actions.queue_value": "Sıra var",
            "lounge.kicker": "Şarj arası",
            "lounge.title": "Salon",
            "lounge.subtitle": "Aracın dolarken reflekslerini açık tutan kısa ve sürprizli bir oyun.",
            "lounge.game_title": "VOLT DASH",
            "lounge.best": "EN İYİ",
            "lounge.score": "SKOR",
            "lounge.start": "Başlat",
            "lounge.jump": "Zıpla",
            "lounge.ready": "Hazır",
            "lounge.running": "Koşuyor",
            "lounge.crashed": "Çarptın",
            "intent.balanced": "Dengeli",
            "intent.near": "Yakın",
            "intent.fast": "Hızlı",
            "intent.economic": "Uygun",
            "badge.risk": "Risk bildirildi",
            "badge.last_positive": "Son bildirim olumlu",
            "badge.no_live": "Canlı veri yok",
            "badge.arrival_safe": "Varış güvenli",
            "badge.arrival_low": "Varış düşük",
            "badge.fast_dc": "Hızlı DC",
            "badge.dc": "DC",
            "badge.sources": "{count} kaynak",
            "badge.high_confidence": "Yüksek veri güveni"
        ],
        .en: [
            "status.ok": "Done",
            "status.error": "Error",
            "data.loading": "Preparing stations",
            "data.refresh": "Try again",
            "data.ready": "{count} stations ready",
            "auth.hero_line1": "Catch",
            "auth.hero_line2": "the charge.",
            "auth.card_title": "Continue with your account",
            "auth.card_hint": "Favorites and reports are saved to your account.",
            "auth.login": "Sign in",
            "auth.register": "Register",
            "auth.reset": "Reset",
            "auth.mode_label": "Account action",
            "auth.continue": "Continue",
            "auth.email": "Email",
            "auth.email_placeholder": "you@example.com",
            "auth.password": "Password",
            "auth.password_placeholder": "Your password",
            "auth.login_action": "Sign in",
            "auth.register_action": "Create account",
            "auth.reset_action": "Send reset link",
            "auth.login_loading": "Signing in...",
            "auth.register_loading": "Creating account...",
            "auth.reset_loading": "Preparing link...",
            "auth.forgot_password": "Forgot password",
            "auth.back_to_login": "Back to sign in",
            "auth.reset_hint": "Enter your email and we will send a reset link.",
            "auth.reset_email_required": "Enter your email to reset your password.",
            "auth.fill_fields": "Enter your email and password.",
            "auth.guest_primary_title": "Find a charger right away",
            "auth.guest_primary_hint": "No membership required. Choose your location and build your route.",
            "auth.guest_primary_action": "Start now",
            "auth.verified_driver": "Verified driver",
            "auth.signed_in_hint": "Favorites and status reports sync with this account.",
            "auth.logout": "Sign out",
            "auth.firebase_config_required": "Add AppConfig.plist to enable Firebase.",
            "bottom.home": "Home",
            "bottom.map": "Lounge",
            "bottom.routes": "Routes",
            "bottom.account": "Account",
            "nav.back": "Back",
            "home.quick_near": "Nearest",
            "home.quick_fast": "Fast",
            "home.quick_value": "Value",
            "home.search_title": "Where are you starting?",
            "home.location_selected": "No location selected",
            "home.use_location": "Use my location",
            "home.location_waiting_authorized": "Getting location. City or coordinate entry opens if no signal arrives.",
            "home.location_waiting_pending": "Waiting for location permission. City or coordinate entry opens if you decline.",
            "home.location_waiting_failed": "Location is unavailable. Continue with a city or coordinates.",
            "home.location_pick": "Choose a city or area",
            "home.latitude": "Latitude",
            "home.longitude": "Longitude",
            "home.use_manual_location": "Use manual location",
            "catalog.kicker": "Driving profile",
            "catalog.charge_percent": "Charge %",
            "catalog.capacity": "Battery capacity",
            "catalog.consumption": "Average consumption",
            "charge.low": "Low",
            "charge.ready": "Ready to drive",
            "charge.long_range": "Long range",
            "charge.label": "Charge",
            "charge.selected_level": "Selected battery level",
            "filters.title": "Filters and driving settings",
            "filters.preference": "Preference",
            "filters.power": "Power",
            "filters.minimum_power": "Minimum {power} kW",
            "filters.socket": "Socket",
            "filters.range": "Hide out-of-range",
            "filters.apply": "Apply",
            "home.insight_kicker": "Smart range suggestion",
            "home.insight_title": "Ready to go with {range} km of safe range",
            "summary.safe_range_value": "%{percent} · {range} km safe range",
            "location.find_charger": "Find the Best Station",
            "location.calculating": "Calculating...",
            "service.firebase_missing": "Firebase settings are not defined in AppConfig.plist.",
            "service.reset_sent": "Password reset link sent.",
            "service.favorite_login_required": "Sign in to save this station.",
            "service.report_login_required": "Sign in to report station status.",
            "service.no_session": "No session.",
            "route.location_required": "Choose a location for the route.",
            "route.idle": "Route is not ready",
            "route.idle_hint": "Choose your location on Home and tap Find the Best Station.",
            "route.searching": "Calculating the best stops",
            "route.failed": "Route could not be calculated",
            "route.empty": "No suitable station found",
            "route.empty_hint": "Try relaxing the filters.",
            "route.back_home": "Back to Home",
            "feed.score": "SCORE",
            "feed.route_approximate": "APPROXIMATE ROUTE",
            "feed.minute": "min",
            "feed.arrival": "arrival",
            "feed.arrival_charge": "Arrival charge",
            "feed.deviation": "Deviation",
            "feed.power": "POWER",
            "feed.socket": "SOCKET",
            "feed.price": "PRICE",
            "feed.detail_card": "CHARGING POINT",
            "feed.open_route": "Open Route",
            "feed.apple_maps": "Apple Maps",
            "feed.google_maps": "Google Maps",
            "feed.open_in_maps": "Open route in Maps",
            "feed.favorite_add": "Add to favorites",
            "feed.favorite_remove": "Remove from favorites",
            "actions.available": "Available",
            "actions.issue_value": "Issue",
            "actions.queue_value": "Queue",
            "lounge.kicker": "Charging break",
            "lounge.title": "Lounge",
            "lounge.subtitle": "A short, surprising reflex game while your vehicle charges.",
            "lounge.game_title": "VOLT DASH",
            "lounge.best": "BEST",
            "lounge.score": "SCORE",
            "lounge.start": "Start",
            "lounge.jump": "Jump",
            "lounge.ready": "Ready",
            "lounge.running": "Running",
            "lounge.crashed": "Crashed",
            "intent.balanced": "Balanced",
            "intent.near": "Nearest",
            "intent.fast": "Fast",
            "intent.economic": "Value",
            "badge.risk": "Risk reported",
            "badge.last_positive": "Last report positive",
            "badge.no_live": "No live data",
            "badge.arrival_safe": "Arrival safe",
            "badge.arrival_low": "Arrival low",
            "badge.fast_dc": "Fast DC",
            "badge.dc": "DC",
            "badge.sources": "{count} sources",
            "badge.high_confidence": "High data confidence"
        ]
    ]
}
