import Foundation

enum AppLanguage: String, CaseIterable, Codable {
    case tr
    case en

    var displayCode: String {
        rawValue.uppercased()
    }

    var locale: Locale {
        switch self {
        case .tr: Locale(identifier: "tr_TR")
        case .en: Locale(identifier: "en_US")
        }
    }

    func uppercased(_ value: String) -> String {
        value.uppercased(with: locale)
    }

    init(code: String) {
        switch code.lowercased() {
        case "en":
            self = .en
        default:
            self = .tr
        }
    }
}

enum AppLocalization {
    static func text(
        _ key: String,
        language: AppLanguage,
        replacements: [String: String] = [:]
    ) -> String {
        var value = translations[language]?[key] ?? translations[.tr]?[key] ?? key
        for (name, replacement) in replacements {
            value = value
                .replacingOccurrences(of: "{\(name)}", with: replacement)
                .replacingOccurrences(of: "{\(name):.0f}", with: replacement)
        }
        return value
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .tr: [
            "status.ok": "Tamam",
            "status.cancel": "Vazgeç",
            "status.yes": "Evet",
            "status.no": "Hayır",
            "status.error": "Hata",
            "network.offline": "Çevrimdışısın · kayıtlı istasyon verileri kullanılıyor",
            "offline.saved": "İşlem cihazına kaydedildi · bağlantı gelince otomatik tamamlanacak",
            "recovery.safe_mode": "Verilerin güvende · geçici okuma modu",
            "data.recovery_failed": "Kayıtlı istasyon verileri açılamadı. Uygulama otomatik kurtarmayı tekrar deneyecek.",
            "data.loading": "İstasyonlar hazırlanıyor",
            "data.refresh": "Tekrar dene",
            "data.ready": "{count} istasyon hazır",
            "data.updated": "{count} istasyon güncellendi",
            "auth.demand_analytics": "Anonim talep paylaşımı",
            "auth.demand_analytics_hint": "Aramalar yaklaşık 11 km'lik bölgelere yuvarlanır. Kimliğin ve tam konumun paylaşılmaz.",
            "auth.privacy": "Gizlilik",
            "auth.terms": "Kullanım koşulları",
            "auth.support": "Destek",
            "auth.about": "Uygulama hakkında",
            "auth.version": "Sürüm {version}",
            "profile.eyebrow": "SENİN ALANIN",
            "profile.title": "Sürüşün.",
            "profile.subtitle": "Favorilerin, şarj geçmişin ve kişisel içgörülerin tek yerde.",
            "profile.privacy_title": "Gizlilik tercihi",
            "profile.data_title": "Verilerini yönet",
            "profile.data_hint": "Favorilerini, bildirimlerini ve anonim cihaz kimliğini buluttan silebilirsin. Uygulamayı kullanmaya kesintisiz devam edersin.",
            "profile.reset_action": "Bulut verilerimi sıfırla",
            "profile.reset_loading": "Veriler sıfırlanıyor...",
            "profile.reset_title": "Bulut verilerini sıfırla?",
            "profile.reset_message": "Favorilerin ve gönderdiğin bildirimler silinir. Bu işlem geri alınamaz.",
            "profile.reset_confirm": "Verileri sıfırla",
            "profile.automation_group": "Akıllı otomasyon",
            "profile.automation_group_hint": "Sistem senin yerine hazırlasın",
            "profile.insights_group": "Kullanım ve kazanç",
            "profile.insights_group_hint": "Geçmiş, maliyet ve tasarruf ayrıntıları",
            "profile.privacy_group": "Gizlilik ve veriler",
            "profile.privacy_group_hint": "İzinler ve veri yönetimi",
            "bottom.home": "Ana Sayfa",
            "bottom.map": "Salon",
            "bottom.routes": "Rotalar",
            "bottom.account": "Profil",
            "navigation.open": "Gezinme menüsünü aç",
            "nav.back": "Geri",
            "home.quick_near": "Yakın",
            "home.quick_fast": "Hızlı",
            "home.quick_value": "Uygun",
            "home.fine_tune": "İnce ayar",
            "home.search_title": "Nereden başlıyorsun?",
            "home.location_selected": "Konum seçilmedi",
            "home.use_location": "Konumumu kullan",
            "home.location_waiting_authorized": "Konum alınıyor. Sinyal gelmezse şehir veya koordinat girişi açılır.",
            "home.location_waiting_pending": "Konum izni bekleniyor. İzin vermezsen şehir veya koordinat girişi açılır.",
            "home.location_waiting_failed": "Konuma erişilemiyor. Şehir veya koordinatla devam edebilirsin.",
            "home.location_pick": "Şehir veya bölge seç",
            "home.latitude": "Enlem",
            "home.longitude": "Boylam",
            "home.use_manual_location": "Manuel konumu kullan",
            "home.open_settings": "Konum izni için Ayarlar'ı aç",
            "place.my_location": "Konumum",
            "place.choose_origin": "Konum seç",
            "place.choose_destination": "Hedef ekle",
            "place.not_selected": "Seçilmedi",
            "place.optional": "İsteğe bağlı",
            "place.clear_destination": "Hedefi kaldır",
            "place.origin_title": "Konum seç",
            "place.destination_title": "Nereye gidiyorsun?",
            "place.origin_hint": "Adres, semt veya yer ara",
            "place.destination_hint": "Hedefini arayarak rota üzerindeki istasyonları bul",
            "place.search_prompt": "Adres veya yer ara",
            "catalog.kicker": "Sürüş profili",
            "catalog.charge_percent": "Şarj %",
            "catalog.capacity": "Batarya kapasitesi",
            "catalog.consumption": "Ortalama tüketim",
            "charge.low": "Düşük",
            "charge.ready": "Yola hazır",
            "charge.long_range": "Uzun menzil",
            "charge.label": "Şarj",
            "charge.selected_level": "Seçili batarya seviyesi",
            "filters.title": "Filtreler ve sürüş ayarları",
            "filters.preference": "Öncelik",
            "filters.power": "Güç",
            "filters.minimum_power": "Minimum {power} kW",
            "filters.socket": "Soket",
            "filters.range": "Menzil dışını gizle",
            "filters.apply": "Uygula",
            "home.insight_kicker": "Akıllı menzil önerisi",
            "home.insight_title": "{range} km güvenli menzille yola hazırsın",
            "home.ready_verified": "Hazır ve doğrulandı",
            "home.ready_distance": "Mesafe",
            "home.ready_duration": "Süre",
            "home.ready_alternatives": "Alternatifleri incele",
            "context.charging_kicker": "Aktif işlem",
            "context.charging_title": "Şarj devam ediyor",
            "context.charging_target": "%{percent} hedefi · Salonu aç",
            "context.critical_kicker": "Kritik menzil",
            "context.critical_title": "Şarjın %{percent} seviyesinde",
            "context.critical_detail": "Yaklaşık {range} km güvenli menzil · İstasyon bul",
            "context.smart_kicker": "Bağlam asistanı",
            "context.defer_offer": "Yaklaşan planını 1 saat erteleyeyim mi?",
            "context.defer_completed": "Yaklaşan planın 1 saat ertelendi",
            "context.recovery_offer": "15 dakikalık sakin bir ara iyi gelebilir",
            "context.health_disclaimer": "Sağlık tanısı değildir; cihazındaki güncel sinyallere dayanır.",
            "context.accept": "Öneriyi uygula",
            "context.dismiss": "Öneriyi kapat",
            "context.settings_title": "Bağlam zekâsı",
            "context.settings_hint": "Takvim, yaklaşık konum, hava, cihazdaki sağlık sinyalleri ve alışkanlıklarını cihaz üzerinde birleştirir.",
            "context.enable": "Bağlamsal önerileri aç",
            "context.health": "HealthKit sinyallerini kullan",
            "context.weather": "Hava durumunu kullan",
            "context.calendar_auto": "Öğrenilen ertelemeleri otomatik uygula",
            "context.calendar_auto_hint": "Otomasyon ancak benzer önerileri en az iki kez kabul ettikten sonra çalışır. Toplantı sahibi olmadığın etkinlikler değiştirilmez.",
            "context.completed_kicker": "Otomatik tamamlandı",
            "context.completed_detail": "Yoğun bağlam algılandı; değişiklik takvimine kaydedildi.",
            "context.notification_title": "Programın rahatlatıldı",
            "context.notification_body": "Yaklaşan takvim öğesini 1 saat erteledim.",
            "summary.safe_range_value": "%{percent} · {range} km güvenli menzil",
            "location.find_charger": "En Uygun İstasyonu Bul",
            "location.calculating": "Hesaplanıyor...",
            "service.firebase_missing": "Firebase ayarları AppConfig.plist içinde tanımlı değil.",
            "service.account_deleted": "Bulut verileri sıfırlandı.",
            "service.no_session": "Oturum yok.",
            "service.too_many_attempts": "Çok fazla deneme yapıldı. Biraz bekleyip tekrar dene.",
            "service.network_error": "Ağ bağlantısı kurulamadı. Bağlantını kontrol edip tekrar dene.",
            "service.report_sent": "Durum bildirimin alındı.",
            "service.report_cooldown": "Yeni bildirim için {seconds} saniye beklemelisin.",
            "deep_link.not_found": "Bu şarj noktası güncel veri kümesinde bulunamadı.",
            "deep_link.location_needed": "Şarj noktasını açmak için önce konumunu seç.",
            "route.location_required": "Rota için konum seçmelisin.",
            "route.idle": "Rota hazır değil",
            "route.idle_hint": "Ana sayfadan konumunu seçip En Uygun İstasyonu Bul'a bas.",
            "route.searching": "En iyi duraklar hesaplanıyor",
            "route.refreshing": "Sonuç doğrulanıyor",
            "route.failed": "Rota hesaplanamadı",
            "route.empty": "Uygun istasyon bulunamadı",
            "route.empty_hint": "Filtreleri gevşetip tekrar deneyebilirsin.",
            "route.location_review": "Bu konum veri kapsamının dışında. Şehir veya koordinat seç.",
            "route.back_home": "Ana Sayfaya Dön",
            "feed.score": "SKOR",
            "feed.route_approximate": "YAKLAŞIK ROTA",
            "feed.route_live": "CANLI ROTA",
            "feed.expand_map": "Haritayı büyüt",
            "feed.best_match": "En uygun seçim",
            "feed.nearby_option": "Yakındaki seçenek",
            "feed.start_route": "Yola Çık",
            "feed.route_options": "Harita seç",
            "feed.more_details": "İstasyon detayları",
            "feed.report_status": "Durum bildir",
            "feed.view_mode": "Görünüm",
            "feed.cards": "Kartlar",
            "feed.alternatives_title": "Alternatifler",
            "feed.alternatives_hint": "En güçlü {count} seçeneği göster",
            "feed.map": "Harita",
            "feed.filters": "Filtreleri aç",
            "map.current_location": "Mevcut konum",
            "map.open_detail": "İstasyon ayrıntılarını aç",
            "feed.minute": "dk",
            "feed.arrival": "varış",
            "feed.arrival_charge": "Varış şarjı",
            "feed.deviation": "Sapma",
            "feed.power": "GÜÇ",
            "feed.socket": "SOKET",
            "feed.price": "FİYAT",
            "feed.detail_card": "ŞARJ NOKTASI",
            "feed.open_route": "Rotayı Aç",
            "feed.apple_maps": "Apple Maps",
            "feed.google_maps": "Google Maps",
            "feed.apple_maps_short": "Apple",
            "feed.google_maps_short": "Google",
            "feed.open_in_maps": "Rotayı Haritalar'da aç",
            "feed.favorite_add": "Favoriye ekle",
            "feed.favorite_remove": "Favoriden çıkar",
            "feed.share": "Şarj noktasını paylaş",
            "story.headline": "Şu an burada\nşarj oluyorum.",
            "story.footer": "ŞarjBul · Elektrikli yolculuk",
            "story.error": "Hikâye görseli hazırlanamadı. Lütfen tekrar dene.",
            "story.preview_title": "Hikâye önizlemesi",
            "story.share_action": "Hikâyeyi paylaş",
            "habit.kicker": "Sana göre",
            "habit.station_message": "{period} {station} rotasını sık açıyorsun.",
            "habit.preference_message": "{period} genellikle {preference} istasyonları seçiyorsun.",
            "habit.local_note": "Bu öneri yalnızca bu cihazdaki kullanımına göre hazırlandı.",
            "habit.open_route": "Rotayı tekrar aç",
            "habit.apply": "Öneriyi uygula",
            "habit.dismiss": "Öneriyi gizle",
            "habit.period_morning": "Sabahları",
            "habit.period_afternoon": "Öğleden sonraları",
            "habit.period_evening": "Akşamları",
            "habit.period_night": "Gece saatlerinde",
            "intent_prefill.applied": "Ayarlar kullanımına göre önceden dolduruldu · %{confidence} eşleşme",
            "intent_prefill.undo": "Geri al",
            "proof.verified_compact": "%{confidence} doğrulanmış sonuç",
            "proof.value_title": "Senin için tamamlananlar",
            "proof.completed_actions": "Hazır sonuç",
            "proof.time_saved": "Tahmini kazanım",
            "proof.average_trust": "Doğrulanan",
            "proof.routes_started": "Başlatılan rota",
            "proof.minutes_value": "{minutes} dk",
            "proof.value_hint": "Yalnızca deterministik kontrolleri geçen ve kanıtı kaydedilen sonuçlar sayılır.",
            "agent.settings_title": "Otonom şarj asistanı",
            "agent.settings_hint": "Şarjın düştüğünde veya istasyon koşulları değiştiğinde veriyi yeniler, güvenli rotayı otomatik optimize eder ve sonucu bildirir.",
            "agent.enable": "Benim için rota hazırla",
            "agent.threshold": "%{percent} altında harekete geç",
            "agent.profile_fallback": "Araç verisi yoksa sürüş profilimi kullan",
            "agent.profile_fallback_hint": "Bağlı üretici veya MFi sağlayıcısı varsa gerçek araç verisi önceliklidir. Aksi halde yalnızca bu cihazdaki şarj ve tüketim değerleri kullanılır.",
            "agent.ready_kicker": "AJAN TAMAMLADI",
            "agent.ready_title": "Senin için uygun bir istasyon buldum",
            "agent.minutes": "{minutes} dk",
            "agent.arrival": "Varış %{percent}",
            "agent.source_profile": "Sürüş profilindeki son değerlere göre hazırlandı.",
            "agent.source_vehicle": "Bağlı aracın güncel verilerine göre hazırlandı.",
            "agent.open_route": "Hazır rotayı aç",
            "agent.snooze": "15 dakika sonra",
            "agent.mute_today": "Bugün önerme",
            "agent.dismiss": "Öneriyi kapat",
            "agent.notification_title": "Senin için rota hazır",
            "agent.notification_body": "{station}, yaklaşık {minutes} dakika uzakta. Seyri başlatmak ister misin?",
            "agent.optimized_notification_title": "Otomatik optimizasyon tamamlandı",
            "agent.optimized_notification_body": "Durumu kontrol ettim ve rotanı {station} için optimize ettim. İstasyon yaklaşık {minutes} dakika uzakta.",
            "agent.report_risky": "Önceki istasyonda risk tespit ettim; rotayı {station} ile güvenli biçimde değiştirdim.",
            "agent.report_expired": "Eski rota artık güncel değildi; {station} için yeni rota hazırladım.",
            "agent.report_refreshed": "İstasyon verilerini yeniledim ve en güncel seçimi {station} olarak hazırladım.",
            "agent.report_low_charge": "Düşük şarjı tespit ettim; {station} için güvenli rotayı hazırladım.",
            "actions.available": "Uygun",
            "actions.issue_value": "Sorun var",
            "actions.queue_value": "Sıra var",
            "actions.station_tools": "İstasyon araçları",
            "lounge.kicker": "Şarj arası",
            "lounge.title": "Salon",
            "lounge.subtitle": "Aracın dolarken reflekslerini açık tutan kısa ve sürprizli bir oyun.",
            "lounge.game_title": "VOLT DASH",
            "lounge.best": "EN İYİ",
            "lounge.score": "SKOR",
            "lounge.start": "Başlat",
            "lounge.jump": "Zıpla",
            "lounge.ready": "Hazır",
            "lounge.running": "Koşuyor",
            "lounge.crashed": "Çarptın",
            "lounge.fullscreen": "Tam ekran oyna",
            "lounge.exit_fullscreen": "Tam ekrandan çık",
            "reminder.title": "Şarj hatırlatıcısı",
            "reminder.hint": "Aracını kontrol etmeyi unutmamak için yerel bir hatırlatıcı kur.",
            "reminder.minutes": "{minutes} dk",
            "reminder.set": "Hatırlat",
            "reminder.cancel": "İptal et",
            "reminder.scheduled": "{minutes} dakika sonrası için hazır.",
            "reminder.cancelled": "Hatırlatıcı iptal edildi.",
            "reminder.denied": "Bildirim izni kapalı. Ayarlar'dan bildirimlere izin verebilirsin.",
            "reminder.notification_title": "Şarjını kontrol et",
            "reminder.notification_body": "Aracının şarj durumuna bakma zamanı geldi.",
            "library.favorites": "Favoriler",
            "library.recent": "Son rotalar",
            "library.empty_favorites": "Henüz favori istasyonun yok.",
            "library.open_route": "Rotayı aç",
            "intent.balanced": "Dengeli",
            "intent.near": "Yakın",
            "intent.fast": "Hızlı",
            "intent.economic": "Uygun",
            "badge.risk": "Risk bildirildi",
            "badge.last_positive": "Son bildirim olumlu",
            "badge.no_live": "Canlı veri yok",
            "badge.arrival_safe": "Varış güvenli",
            "badge.arrival_low": "Varış düşük",
            "badge.fast_dc": "Hızlı DC",
            "badge.dc": "DC",
            "badge.sources": "{count} kaynak",
            "badge.high_confidence": "Yüksek veri güveni",
            "data_quality.title": "İstasyon bilgisini doğrula",
            "data_quality.explanation": "Katkın diğer sürücülerin daha doğru karar vermesine yardım eder. İki bağımsız onaydan sonra bilgi doğrulanmış sayılır.",
            "data_quality.station_details": "İstasyon bilgileri",
            "data_quality.address": "Adres",
            "data_quality.night_safety": "Gece güvenliği",
            "data_quality.lighting": "Aydınlatma",
            "data_quality.camera": "Kamera",
            "data_quality.open_24h": "7/24 açık işletme",
            "data_quality.unknown": "Bilmiyorum",
            "data_quality.confirm": "Bilgileri doğrula",
            "data_quality.independent_note": "Güven puanı onay yaşı ve bağımsız kullanıcı sayısına göre zamanla güncellenir.",
            "data_quality.improve": "Bilgiyi doğrula veya düzelt",
            "data_quality.improve_short": "Bilgiyi doğrula",
            "data_quality.thanks": "Katkın alındı. Teşekkürler.",
            "insight.live_availability": "Canlı: {available}/{total} soket uygun",
            "insight.busy_prediction": "Bu saatte dolu olma ihtimali %{percent} · tahmin",
            "insight.data_confidence": "Veri güveni %{percent}",
            "insight.operator_match": "EPDK lisansı eşleşti",
            "decision.arrival": "VARIŞ",
            "decision.availability": "MÜSAİTLİK",
            "decision.charge_target": "%{percent}'E ŞARJ",
            "decision.minutes": "~{minutes} dk",
            "decision.live_count": "{available}/{total} boş",
            "decision.busy": "%{percent} yoğun",
            "decision.available": "%{percent} uygun",
            "decision.risky": "Riskli",
            "decision.unknown": "Veri yok",
            "decision.technical_details": "Teknik detaylar",
            "planner.title": "Şarj planı",
            "planner.fastest_plan": "Sürüş + şarj için en kısa plan",
            "planner.distance": "MESAFE",
            "planner.charge_time": "ŞARJ",
            "planner.arrival": "VARIŞ",
            "planner.stops": "Önerilen duraklar",
            "planner.no_stop": "Hedefe şarj molası vermeden ulaşabilirsin.",
            "planner.stop_detail": "%{arrival} ile var · %{departure} ile çık · {minutes} dk",
            "planner.minutes": "{minutes} dk",
            "planner.hours_minutes": "{hours} sa {minutes} dk",
            "planner.elevation_attribution": "Tüketim rakıma göre düzeltildi. Rakım: Copernicus DEM / Open-Meteo.",
            "planner.elevation_unavailable": "Rakım servisine ulaşılamadı; plan düz yol tüketimiyle hesaplandı.",
            "planner.holiday_advice": "{holiday} modu: {start}:00–{end}:00 arasında ana koridorda yoğunluk bekleniyor.",
            "history.title": "Şarj günlüğü",
            "history.subtitle": "Fişini tara, harcamanı ve elektrikli yolculuğunu takip et.",
            "history.scan_receipt": "Şarj fişi tara",
            "history.sessions": "ŞARJ",
            "history.spending": "HARCAMA",
            "history.co2": "CO₂ TASARRUFU",
            "history.province_progress": "81 ilin {count} tanesi",
            "history.share": "Özetini paylaş",
            "history.receipt_values": "Okunan değerler",
            "history.energy": "Enerji (kWh)",
            "history.cost": "Toplam (TL)",
            "history.station": "İstasyonla eşleştir",
            "history.station_unknown": "İstasyon belirtilmedi",
            "history.confirm_receipt": "Fişi doğrula",
            "history.save": "Kaydet",
            "history.scan_failed": "Fişte kWh veya tutar okunamadı. Daha net bir fotoğraf dene.",
            "history.wrapped": "{year} ŞarjBul özetim: {sessions} şarj, yaklaşık {distance} km elektrikli yolculuk ve {co2} kg CO₂ tasarrufu.",
            "history.collections": "Yolculuk koleksiyonları",
            "history.collection_progress": "{visited}/{total} il",
            "history.collection_complete": "Tamamlandı",
            "history.collection_east_express": "Doğu Ekspresi",
            "history.collection_aegean_tour": "Ege Turu",
            "history.collection_black_sea": "Karadeniz Yaylacısı",
            "break.start": "Şarj molasını başlat",
            "break.start_short": "Mola başlat",
            "break.title": "Mola asistanı",
            "break.loading": "400 metre içindeki yerler aranıyor",
            "break.empty": "Yakında uygun bir mola noktası bulunamadı.",
            "break.finish": "Şarj molasını bitir",
            "legal.privacy_title": "Gizlilik politikası",
            "legal.privacy_body": "ŞarjBul giriş veya kayıt istemez. Favori ve bildirimleri güvenli biçimde ayırmak için cihazda saklanan anonim Firebase kimliği kullanılır; e-posta veya şifre işlenmez. Konum yalnızca istasyon bulma ve rota hesabında kullanılır. Crashlytics teknik çökme verilerini kararlılık için işleyebilir, App Check yetkisiz erişimi azaltır. Veriler reklam veya takip amacıyla kullanılmaz. Bulut verilerini Profil ekranından sıfırlayabilirsin.",
            "legal.terms_title": "Kullanım koşulları",
            "legal.terms_body": "İstasyon, fiyat, uygunluk, menzil ve rota bilgileri karar desteği sağlar; gerçek yol ve operatör verileri değişebilir. Sürüş sırasında cihazı kullanma. Yola çıkmadan önce aracının menzilini, yol koşullarını ve istasyonun operatör bilgilerini doğrula.",
            "legal.support_title": "Destek",
            "legal.support_body": "Bir veri hatası veya erişilebilirlik problemi bildirirken istasyon adını ve yaşadığın adımları ekle.",
            "legal.open_web": "Web sayfasını aç",
            "legal.email": "E-posta gönder"
        ],
        .en: [
            "status.ok": "Done",
            "status.cancel": "Cancel",
            "status.yes": "Yes",
            "status.no": "No",
            "status.error": "Error",
            "network.offline": "You're offline · saved station data is in use",
            "offline.saved": "Saved on this device · it will finish automatically when connection returns",
            "recovery.safe_mode": "Your data is safe · temporary read-only mode",
            "data.recovery_failed": "Saved station data could not be opened. The app will retry recovery automatically.",
            "data.loading": "Preparing stations",
            "data.refresh": "Try again",
            "data.ready": "{count} stations ready",
            "data.updated": "{count} stations updated",
            "auth.demand_analytics": "Anonymous demand sharing",
            "auth.demand_analytics_hint": "Searches are rounded to roughly 11 km areas. Your identity and precise location are not shared.",
            "auth.privacy": "Privacy",
            "auth.terms": "Terms of use",
            "auth.support": "Support",
            "auth.about": "About the app",
            "auth.version": "Version {version}",
            "profile.eyebrow": "YOUR SPACE",
            "profile.title": "Your drive.",
            "profile.subtitle": "Favorites, charging history, and personal insights in one place.",
            "profile.privacy_title": "Privacy preference",
            "profile.data_title": "Manage your data",
            "profile.data_hint": "Delete favorites, reports, and the anonymous device identity from the cloud. You can keep using the app without interruption.",
            "profile.reset_action": "Reset my cloud data",
            "profile.reset_loading": "Resetting data...",
            "profile.reset_title": "Reset cloud data?",
            "profile.reset_message": "Your favorites and submitted reports will be deleted. This cannot be undone.",
            "profile.reset_confirm": "Reset data",
            "profile.automation_group": "Smart automation",
            "profile.automation_group_hint": "Let the system prepare the result",
            "profile.insights_group": "Usage and value",
            "profile.insights_group_hint": "History, cost, and savings details",
            "profile.privacy_group": "Privacy and data",
            "profile.privacy_group_hint": "Permissions and data controls",
            "bottom.home": "Home",
            "bottom.map": "Lounge",
            "bottom.routes": "Routes",
            "bottom.account": "Profile",
            "navigation.open": "Open navigation menu",
            "nav.back": "Back",
            "home.quick_near": "Nearest",
            "home.quick_fast": "Fast",
            "home.quick_value": "Value",
            "home.fine_tune": "Fine tune",
            "home.search_title": "Where are you starting?",
            "home.location_selected": "No location selected",
            "home.use_location": "Use my location",
            "home.location_waiting_authorized": "Getting location. City or coordinate entry opens if no signal arrives.",
            "home.location_waiting_pending": "Waiting for location permission. City or coordinate entry opens if you decline.",
            "home.location_waiting_failed": "Location is unavailable. Continue with a city or coordinates.",
            "home.location_pick": "Choose a city or area",
            "home.latitude": "Latitude",
            "home.longitude": "Longitude",
            "home.use_manual_location": "Use manual location",
            "home.open_settings": "Open Settings for location access",
            "place.my_location": "My location",
            "place.choose_origin": "Choose location",
            "place.choose_destination": "Add destination",
            "place.not_selected": "Not selected",
            "place.optional": "Optional",
            "place.clear_destination": "Remove destination",
            "place.origin_title": "Choose location",
            "place.destination_title": "Where are you going?",
            "place.origin_hint": "Search for an address, area, or place",
            "place.destination_hint": "Search your destination to find chargers along the route",
            "place.search_prompt": "Search address or place",
            "catalog.kicker": "Driving profile",
            "catalog.charge_percent": "Charge %",
            "catalog.capacity": "Battery capacity",
            "catalog.consumption": "Average consumption",
            "charge.low": "Low",
            "charge.ready": "Ready to drive",
            "charge.long_range": "Long range",
            "charge.label": "Charge",
            "charge.selected_level": "Selected battery level",
            "filters.title": "Filters and driving settings",
            "filters.preference": "Preference",
            "filters.power": "Power",
            "filters.minimum_power": "Minimum {power} kW",
            "filters.socket": "Socket",
            "filters.range": "Hide out-of-range",
            "filters.apply": "Apply",
            "home.insight_kicker": "Smart range suggestion",
            "home.insight_title": "Ready to go with {range} km of safe range",
            "home.ready_verified": "Ready and verified",
            "home.ready_distance": "Distance",
            "home.ready_duration": "Time",
            "home.ready_alternatives": "View alternatives",
            "context.charging_kicker": "Active session",
            "context.charging_title": "Charging in progress",
            "context.charging_target": "%{percent} target · Open Lounge",
            "context.critical_kicker": "Critical range",
            "context.critical_title": "Charge is at %{percent}",
            "context.critical_detail": "About {range} km safe range · Find a station",
            "context.smart_kicker": "Context assistant",
            "context.defer_offer": "Move your next plan one hour later?",
            "context.defer_completed": "Your next plan was moved by one hour",
            "context.recovery_offer": "A calm 15-minute pause may help",
            "context.health_disclaimer": "Not a medical diagnosis; based on recent on-device signals.",
            "context.accept": "Apply suggestion",
            "context.dismiss": "Dismiss suggestion",
            "context.settings_title": "Context intelligence",
            "context.settings_hint": "Combines calendar, approximate location, weather, on-device health signals and habits on your device.",
            "context.enable": "Enable contextual suggestions",
            "context.health": "Use HealthKit signals",
            "context.weather": "Use weather context",
            "context.calendar_auto": "Apply learned deferrals automatically",
            "context.calendar_auto_hint": "Automation starts only after you accept similar suggestions at least twice. Events owned by others are never changed.",
            "context.completed_kicker": "Completed automatically",
            "context.completed_detail": "A high-load context was detected and the change was saved to your calendar.",
            "context.notification_title": "Your schedule was eased",
            "context.notification_body": "I moved your next calendar item one hour later.",
            "summary.safe_range_value": "%{percent} · {range} km safe range",
            "location.find_charger": "Find the Best Station",
            "location.calculating": "Calculating...",
            "service.firebase_missing": "Firebase settings are not defined in AppConfig.plist.",
            "service.account_deleted": "Cloud data reset.",
            "service.no_session": "No session.",
            "service.too_many_attempts": "Too many attempts. Wait a moment and try again.",
            "service.network_error": "Could not connect. Check your connection and try again.",
            "service.report_sent": "Your station report was received.",
            "service.report_cooldown": "Wait {seconds} seconds before sending another report.",
            "deep_link.not_found": "This charging point is not in the current data set.",
            "deep_link.location_needed": "Choose your location before opening this charging point.",
            "route.location_required": "Choose a location for the route.",
            "route.idle": "Route is not ready",
            "route.idle_hint": "Choose your location on Home and tap Find the Best Station.",
            "route.searching": "Calculating the best stops",
            "route.refreshing": "Verifying result",
            "route.failed": "Route could not be calculated",
            "route.empty": "No suitable station found",
            "route.empty_hint": "Try relaxing the filters.",
            "route.location_review": "This location is outside the data coverage. Choose a city or coordinates.",
            "route.back_home": "Back to Home",
            "feed.score": "SCORE",
            "feed.route_approximate": "APPROXIMATE ROUTE",
            "feed.route_live": "LIVE ROUTE",
            "feed.expand_map": "Expand map",
            "feed.best_match": "Best match",
            "feed.nearby_option": "Nearby option",
            "feed.start_route": "Start Route",
            "feed.route_options": "Choose maps app",
            "feed.more_details": "Station details",
            "feed.report_status": "Report status",
            "feed.view_mode": "View",
            "feed.cards": "Cards",
            "feed.alternatives_title": "Alternatives",
            "feed.alternatives_hint": "Show the strongest {count} options",
            "feed.map": "Map",
            "feed.filters": "Open filters",
            "map.current_location": "Current location",
            "map.open_detail": "Open station details",
            "feed.minute": "min",
            "feed.arrival": "arrival",
            "feed.arrival_charge": "Arrival charge",
            "feed.deviation": "Deviation",
            "feed.power": "POWER",
            "feed.socket": "SOCKET",
            "feed.price": "PRICE",
            "feed.detail_card": "CHARGING POINT",
            "feed.open_route": "Open Route",
            "feed.apple_maps": "Apple Maps",
            "feed.google_maps": "Google Maps",
            "feed.apple_maps_short": "Apple",
            "feed.google_maps_short": "Google",
            "feed.open_in_maps": "Open route in Maps",
            "feed.favorite_add": "Add to favorites",
            "feed.favorite_remove": "Remove from favorites",
            "feed.share": "Share charging point",
            "story.headline": "Charging here\nright now.",
            "story.footer": "ŞarjBul · Electric journey",
            "story.error": "The story image could not be created. Please try again.",
            "story.preview_title": "Story preview",
            "story.share_action": "Share story",
            "habit.kicker": "For you",
            "habit.station_message": "You often open the route to {station} {period}.",
            "habit.preference_message": "You usually choose {preference} stations {period}.",
            "habit.local_note": "This suggestion is based only on activity stored on this device.",
            "habit.open_route": "Open route again",
            "habit.apply": "Apply suggestion",
            "habit.dismiss": "Hide suggestion",
            "habit.period_morning": "in the morning",
            "habit.period_afternoon": "in the afternoon",
            "habit.period_evening": "in the evening",
            "habit.period_night": "at night",
            "intent_prefill.applied": "Settings prefilled from your activity · {confidence}% match",
            "intent_prefill.undo": "Undo",
            "proof.verified_compact": "{confidence}% verified outcome",
            "proof.value_title": "Completed for you",
            "proof.completed_actions": "Ready outcomes",
            "proof.time_saved": "Estimated saved",
            "proof.average_trust": "Verified",
            "proof.routes_started": "Routes started",
            "proof.minutes_value": "{minutes} min",
            "proof.value_hint": "Only outcomes that pass deterministic checks and retain evidence are counted.",
            "agent.settings_title": "Autonomous charging assistant",
            "agent.settings_hint": "When charge runs low or station conditions change, it refreshes the data, safely optimizes the route, and reports the result.",
            "agent.enable": "Prepare routes for me",
            "agent.threshold": "Act below {percent}%",
            "agent.profile_fallback": "Use my driving profile without vehicle data",
            "agent.profile_fallback_hint": "Live data from a connected manufacturer or MFi provider takes priority. Otherwise, only charge and consumption values stored on this device are used.",
            "agent.ready_kicker": "AGENT COMPLETED",
            "agent.ready_title": "I found a suitable station for you",
            "agent.minutes": "{minutes} min",
            "agent.arrival": "Arrive {percent}%",
            "agent.source_profile": "Prepared from the latest values in your driving profile.",
            "agent.source_vehicle": "Prepared from current data supplied by your connected vehicle.",
            "agent.open_route": "Open ready route",
            "agent.snooze": "Remind me in 15 minutes",
            "agent.mute_today": "No more today",
            "agent.dismiss": "Dismiss suggestion",
            "agent.notification_title": "Your route is ready",
            "agent.notification_body": "{station} is about {minutes} minutes away. Start navigation?",
            "agent.optimized_notification_title": "Automatic optimization complete",
            "agent.optimized_notification_body": "I checked current conditions and optimized your route for {station}, about {minutes} minutes away.",
            "agent.report_risky": "I detected risk at the previous station and safely switched the route to {station}.",
            "agent.report_expired": "The previous route was outdated, so I prepared a new route to {station}.",
            "agent.report_refreshed": "I refreshed station data and prepared {station} as the current best choice.",
            "agent.report_low_charge": "I detected low charge and prepared a safe route to {station}.",
            "actions.available": "Available",
            "actions.issue_value": "Issue",
            "actions.queue_value": "Queue",
            "actions.station_tools": "Station tools",
            "lounge.kicker": "Charging break",
            "lounge.title": "Lounge",
            "lounge.subtitle": "A short, surprising reflex game while your vehicle charges.",
            "lounge.game_title": "VOLT DASH",
            "lounge.best": "BEST",
            "lounge.score": "SCORE",
            "lounge.start": "Start",
            "lounge.jump": "Jump",
            "lounge.ready": "Ready",
            "lounge.running": "Running",
            "lounge.crashed": "Crashed",
            "lounge.fullscreen": "Play full screen",
            "lounge.exit_fullscreen": "Exit full screen",
            "reminder.title": "Charging reminder",
            "reminder.hint": "Set a local reminder so you do not forget to check your vehicle.",
            "reminder.minutes": "{minutes} min",
            "reminder.set": "Remind me",
            "reminder.cancel": "Cancel",
            "reminder.scheduled": "Ready for {minutes} minutes from now.",
            "reminder.cancelled": "Reminder cancelled.",
            "reminder.denied": "Notifications are disabled. You can enable them in Settings.",
            "reminder.notification_title": "Check your charge",
            "reminder.notification_body": "It is time to check your vehicle's charging status.",
            "library.favorites": "Favorites",
            "library.recent": "Recent routes",
            "library.empty_favorites": "You have no favorite stations yet.",
            "library.open_route": "Open route",
            "intent.balanced": "Balanced",
            "intent.near": "Nearest",
            "intent.fast": "Fast",
            "intent.economic": "Value",
            "badge.risk": "Risk reported",
            "badge.last_positive": "Last report positive",
            "badge.no_live": "No live data",
            "badge.arrival_safe": "Arrival safe",
            "badge.arrival_low": "Arrival low",
            "badge.fast_dc": "Fast DC",
            "badge.dc": "DC",
            "badge.sources": "{count} sources",
            "badge.high_confidence": "High data confidence",
            "data_quality.title": "Verify station details",
            "data_quality.explanation": "Your contribution helps other drivers make better decisions. A value becomes verified after two independent confirmations.",
            "data_quality.station_details": "Station details",
            "data_quality.address": "Address",
            "data_quality.night_safety": "Night safety",
            "data_quality.lighting": "Lighting",
            "data_quality.camera": "Camera",
            "data_quality.open_24h": "24/7 business nearby",
            "data_quality.unknown": "Not sure",
            "data_quality.confirm": "Verify details",
            "data_quality.independent_note": "Confidence changes over time based on confirmation age and independent users.",
            "data_quality.improve": "Verify or correct details",
            "data_quality.improve_short": "Verify details",
            "data_quality.thanks": "Contribution received. Thank you.",
            "insight.live_availability": "Live: {available}/{total} connectors available",
            "insight.busy_prediction": "%{percent} chance of being busy now · estimate",
            "insight.data_confidence": "%{percent} data confidence",
            "insight.operator_match": "EPDK license match",
            "decision.arrival": "ARRIVAL",
            "decision.availability": "AVAILABILITY",
            "decision.charge_target": "CHARGE TO {percent}%",
            "decision.minutes": "~{minutes} min",
            "decision.live_count": "{available}/{total} free",
            "decision.busy": "{percent}% busy",
            "decision.available": "{percent}% likely",
            "decision.risky": "At risk",
            "decision.unknown": "No data",
            "decision.technical_details": "Technical details",
            "planner.title": "Charging plan",
            "planner.fastest_plan": "Fastest driving + charging plan",
            "planner.distance": "DISTANCE",
            "planner.charge_time": "CHARGING",
            "planner.arrival": "ARRIVAL",
            "planner.stops": "Recommended stops",
            "planner.no_stop": "You can reach the destination without a charging stop.",
            "planner.stop_detail": "Arrive %{arrival} · leave %{departure} · {minutes} min",
            "planner.minutes": "{minutes} min",
            "planner.hours_minutes": "{hours} hr {minutes} min",
            "planner.elevation_attribution": "Consumption is elevation-adjusted. Elevation: Copernicus DEM / Open-Meteo.",
            "planner.elevation_unavailable": "Elevation service unavailable; the plan uses flat-road consumption.",
            "planner.holiday_advice": "{holiday} mode: expect peak corridor demand between {start}:00 and {end}:00.",
            "history.title": "Charging journal",
            "history.subtitle": "Scan a receipt to track spending and electric journeys.",
            "history.scan_receipt": "Scan charging receipt",
            "history.sessions": "SESSIONS",
            "history.spending": "SPENDING",
            "history.co2": "CO₂ SAVED",
            "history.province_progress": "{count} of 81 provinces",
            "history.share": "Share summary",
            "history.receipt_values": "Recognized values",
            "history.energy": "Energy (kWh)",
            "history.cost": "Total (TRY)",
            "history.station": "Match a station",
            "history.station_unknown": "Station not specified",
            "history.confirm_receipt": "Confirm receipt",
            "history.save": "Save",
            "history.scan_failed": "No kWh or total was recognized. Try a clearer photo.",
            "history.wrapped": "My {year} SarjBul recap: {sessions} charges, about {distance} km electric driving and {co2} kg of CO₂ avoided.",
            "history.collections": "Journey collections",
            "history.collection_progress": "{visited}/{total} provinces",
            "history.collection_complete": "Completed",
            "history.collection_east_express": "Eastern Express",
            "history.collection_aegean_tour": "Aegean Tour",
            "history.collection_black_sea": "Black Sea Highlands",
            "break.start": "Start charging break",
            "break.start_short": "Start break",
            "break.title": "Break assistant",
            "break.loading": "Finding places within 400 meters",
            "break.empty": "No suitable break place was found nearby.",
            "break.finish": "Finish charging break",
            "legal.privacy_title": "Privacy policy",
            "legal.privacy_body": "SarjBul does not ask you to sign in or register. An anonymous Firebase identity stored on the device separates favorites and reports securely; no email or password is processed. Location is used only to find stations and calculate routes. Crashlytics may process technical crash data for stability, while App Check reduces unauthorized access. Data is not used for advertising or tracking. You can reset cloud data from the Profile screen.",
            "legal.terms_title": "Terms of use",
            "legal.terms_body": "Station, price, availability, range, and route information is decision support and may differ from current road or operator data. Do not operate the device while driving. Verify your vehicle range, road conditions, and operator information before departure.",
            "legal.support_title": "Support",
            "legal.support_body": "When reporting a data or accessibility issue, include the station name and the steps that led to the problem.",
            "legal.open_web": "Open web page",
            "legal.email": "Send email"
        ]
    ]
}
