import Foundation

enum AppLanguage: String, CaseIterable, Codable {
    case tr
    case en

    var displayCode: String {
        rawValue.uppercased()
    }

    init(code: String) {
        switch code.lowercased() {
        case "en":
            self = .en
        default:
            self = .tr
        }
    }
}

enum AppLocalization {
    static func text(
        _ key: String,
        language: AppLanguage,
        replacements: [String: String] = [:]
    ) -> String {
        var value = translations[language]?[key] ?? translations[.tr]?[key] ?? key
        for (name, replacement) in replacements {
            value = value
                .replacingOccurrences(of: "{\(name)}", with: replacement)
                .replacingOccurrences(of: "{\(name):.0f}", with: replacement)
        }
        return value
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .tr: [
            "status.ok": "Tamam",
            "status.error": "Hata",
            "network.offline": "Çevrimdışısın · kayıtlı istasyon verileri kullanılıyor",
            "data.loading": "İstasyonlar hazırlanıyor",
            "data.refresh": "Tekrar dene",
            "data.ready": "{count} istasyon hazır",
            "data.updated": "{count} istasyon güncellendi",
            "auth.hero_line1": "Akımı",
            "auth.hero_line2": "yakala.",
            "auth.card_title": "Hesabınla devam et",
            "auth.card_hint": "Favoriler ve bildirimler hesabına kaydedilir.",
            "auth.login": "Giriş",
            "auth.register": "Kayıt",
            "auth.reset": "Sıfırla",
            "auth.mode_label": "Hesap işlemi",
            "auth.continue": "Devam et",
            "auth.email": "E-posta",
            "auth.email_placeholder": "sen@ornek.com",
            "auth.password": "Şifre",
            "auth.password_placeholder": "Şifren",
            "auth.login_action": "Giriş yap",
            "auth.register_action": "Kaydol",
            "auth.reset_action": "Sıfırlama Bağlantısı Gönder",
            "auth.login_loading": "Giriş yapılıyor...",
            "auth.register_loading": "Hesap oluşturuluyor...",
            "auth.reset_loading": "Bağlantı hazırlanıyor...",
            "auth.forgot_password": "Şifremi unuttum",
            "auth.back_to_login": "Girişe dön",
            "auth.reset_hint": "E-postanı yaz, sıfırlama bağlantısını gönderelim.",
            "auth.reset_email_required": "Sıfırlama için e-posta adresini yaz.",
            "auth.fill_fields": "E-posta ve şifre alanlarını doldur.",
            "auth.guest_primary_title": "En yakın şarjı hemen bul",
            "auth.guest_primary_hint": "Üyelik gerekmez. Konumunu seçip rotanı oluşturabilirsin.",
            "auth.guest_primary_action": "Hemen başla",
            "auth.verified_driver": "Doğrulanmış sürücü",
            "auth.signed_in_hint": "Favoriler ve durum bildirimleri bu hesapla senkronize edilir.",
            "auth.logout": "Çıkış yap",
            "auth.delete_account": "Hesabı sil",
            "auth.delete_title": "Hesabını kalıcı olarak sil?",
            "auth.delete_message": "Hesabın, favorilerin ve ilişkili verilerin için silme işlemi başlatılır. Bu işlem geri alınamaz.",
            "auth.delete_confirm": "Kalıcı olarak sil",
            "auth.delete_cancel": "Vazgeç",
            "auth.delete_loading": "Hesap siliniyor...",
            "auth.privacy": "Gizlilik",
            "auth.terms": "Kullanım koşulları",
            "auth.support": "Destek",
            "auth.about": "Uygulama hakkında",
            "auth.version": "Sürüm {version}",
            "auth.firebase_config_required": "Firebase ayarları için AppConfig.plist eklenmeli.",
            "bottom.home": "Ana Sayfa",
            "bottom.map": "Salon",
            "bottom.routes": "Rotalar",
            "bottom.account": "Hesap",
            "navigation.open": "Gezinme menüsünü aç",
            "nav.back": "Geri",
            "home.quick_near": "Yakın",
            "home.quick_fast": "Hızlı",
            "home.quick_value": "Uygun",
            "home.search_title": "Nereden başlıyorsun?",
            "home.location_selected": "Konum seçilmedi",
            "home.use_location": "Konumumu kullan",
            "home.location_waiting_authorized": "Konum alınıyor. Sinyal gelmezse şehir veya koordinat girişi açılır.",
            "home.location_waiting_pending": "Konum izni bekleniyor. İzin vermezsen şehir veya koordinat girişi açılır.",
            "home.location_waiting_failed": "Konuma erişilemiyor. Şehir veya koordinatla devam edebilirsin.",
            "home.location_pick": "Şehir veya bölge seç",
            "home.latitude": "Enlem",
            "home.longitude": "Boylam",
            "home.use_manual_location": "Manuel konumu kullan",
            "home.open_settings": "Konum izni için Ayarlar'ı aç",
            "place.my_location": "Konumum",
            "place.choose_origin": "Başlangıç seç",
            "place.choose_destination": "Hedef ekle",
            "place.not_selected": "Seçilmedi",
            "place.optional": "İsteğe bağlı",
            "place.clear_destination": "Hedefi kaldır",
            "place.origin_title": "Başlangıç noktası",
            "place.destination_title": "Nereye gidiyorsun?",
            "place.origin_hint": "Adres, semt veya yer ara",
            "place.destination_hint": "Hedefini arayarak rota üzerindeki istasyonları bul",
            "place.search_prompt": "Adres veya yer ara",
            "catalog.kicker": "Sürüş profili",
            "catalog.charge_percent": "Şarj %",
            "catalog.capacity": "Batarya kapasitesi",
            "catalog.consumption": "Ortalama tüketim",
            "charge.low": "Düşük",
            "charge.ready": "Yola hazır",
            "charge.long_range": "Uzun menzil",
            "charge.label": "Şarj",
            "charge.selected_level": "Seçili batarya seviyesi",
            "filters.title": "Filtreler ve sürüş ayarları",
            "filters.preference": "Öncelik",
            "filters.power": "Güç",
            "filters.minimum_power": "Minimum {power} kW",
            "filters.socket": "Soket",
            "filters.range": "Menzil dışını gizle",
            "filters.apply": "Uygula",
            "home.insight_kicker": "Akıllı menzil önerisi",
            "home.insight_title": "{range} km güvenli menzille yola hazırsın",
            "summary.safe_range_value": "%{percent} · {range} km güvenli menzil",
            "location.find_charger": "En Uygun İstasyonu Bul",
            "location.calculating": "Hesaplanıyor...",
            "service.firebase_missing": "Firebase ayarları AppConfig.plist içinde tanımlı değil.",
            "service.reset_sent": "Şifre sıfırlama bağlantısı gönderildi.",
            "service.verification_sent": "Hesap oluşturuldu. E-posta doğrulama bağlantısı gönderildi.",
            "service.verification_pending": "Hesap oluşturuldu ancak doğrulama e-postası gönderilemedi. Daha sonra tekrar dene.",
            "service.account_deleted": "Hesap silindi.",
            "service.favorite_login_required": "Kaydetmek için giriş yapmalısın.",
            "service.report_login_required": "Durum bildirmek için giriş yapmalısın.",
            "service.no_session": "Oturum yok.",
            "service.invalid_credentials": "E-posta veya şifre hatalı.",
            "service.email_exists": "Bu e-posta ile daha önce hesap oluşturulmuş.",
            "service.weak_password": "Şifre en az 6 karakter olmalı.",
            "service.too_many_attempts": "Çok fazla deneme yapıldı. Biraz bekleyip tekrar dene.",
            "service.network_error": "Ağ bağlantısı kurulamadı. Bağlantını kontrol edip tekrar dene.",
            "service.report_sent": "Durum bildirimin alındı.",
            "service.report_cooldown": "Yeni bildirim için {seconds} saniye beklemelisin.",
            "deep_link.not_found": "Bu şarj noktası güncel veri kümesinde bulunamadı.",
            "deep_link.location_needed": "Şarj noktasını açmak için önce konumunu seç.",
            "route.location_required": "Rota için konum seçmelisin.",
            "route.idle": "Rota hazır değil",
            "route.idle_hint": "Ana sayfadan konumunu seçip En Uygun İstasyonu Bul'a bas.",
            "route.searching": "En iyi duraklar hesaplanıyor",
            "route.failed": "Rota hesaplanamadı",
            "route.empty": "Uygun istasyon bulunamadı",
            "route.empty_hint": "Filtreleri gevşetip tekrar deneyebilirsin.",
            "route.back_home": "Ana Sayfaya Dön",
            "feed.score": "SKOR",
            "feed.route_approximate": "YAKLAŞIK ROTA",
            "feed.route_live": "CANLI ROTA",
            "feed.expand_map": "Haritayı büyüt",
            "feed.view_mode": "Görünüm",
            "feed.cards": "Kartlar",
            "feed.map": "Harita",
            "feed.filters": "Filtreleri aç",
            "map.current_location": "Mevcut konum",
            "map.open_detail": "İstasyon ayrıntılarını aç",
            "feed.minute": "dk",
            "feed.arrival": "varış",
            "feed.arrival_charge": "Varış şarjı",
            "feed.deviation": "Sapma",
            "feed.power": "GÜÇ",
            "feed.socket": "SOKET",
            "feed.price": "FİYAT",
            "feed.detail_card": "ŞARJ NOKTASI",
            "feed.open_route": "Rotayı Aç",
            "feed.apple_maps": "Apple Maps",
            "feed.google_maps": "Google Maps",
            "feed.apple_maps_short": "Apple",
            "feed.google_maps_short": "Google",
            "feed.open_in_maps": "Rotayı Haritalar'da aç",
            "feed.favorite_add": "Favoriye ekle",
            "feed.favorite_remove": "Favoriden çıkar",
            "feed.share": "Şarj noktasını paylaş",
            "actions.available": "Uygun",
            "actions.issue_value": "Sorun var",
            "actions.queue_value": "Sıra var",
            "lounge.kicker": "Şarj arası",
            "lounge.title": "Salon",
            "lounge.subtitle": "Aracın dolarken reflekslerini açık tutan kısa ve sürprizli bir oyun.",
            "lounge.game_title": "VOLT DASH",
            "lounge.best": "EN İYİ",
            "lounge.score": "SKOR",
            "lounge.start": "Başlat",
            "lounge.jump": "Zıpla",
            "lounge.ready": "Hazır",
            "lounge.running": "Koşuyor",
            "lounge.crashed": "Çarptın",
            "reminder.title": "Şarj hatırlatıcısı",
            "reminder.hint": "Aracını kontrol etmeyi unutmamak için yerel bir hatırlatıcı kur.",
            "reminder.minutes": "{minutes} dk",
            "reminder.set": "Hatırlat",
            "reminder.cancel": "İptal et",
            "reminder.scheduled": "{minutes} dakika sonrası için hazır.",
            "reminder.cancelled": "Hatırlatıcı iptal edildi.",
            "reminder.denied": "Bildirim izni kapalı. Ayarlar'dan bildirimlere izin verebilirsin.",
            "reminder.notification_title": "Şarjını kontrol et",
            "reminder.notification_body": "Aracının şarj durumuna bakma zamanı geldi.",
            "library.favorites": "Favoriler",
            "library.recent": "Son rotalar",
            "library.empty_favorites": "Henüz favori istasyonun yok.",
            "library.open_route": "Rotayı aç",
            "intent.balanced": "Dengeli",
            "intent.near": "Yakın",
            "intent.fast": "Hızlı",
            "intent.economic": "Uygun",
            "badge.risk": "Risk bildirildi",
            "badge.last_positive": "Son bildirim olumlu",
            "badge.no_live": "Canlı veri yok",
            "badge.arrival_safe": "Varış güvenli",
            "badge.arrival_low": "Varış düşük",
            "badge.fast_dc": "Hızlı DC",
            "badge.dc": "DC",
            "badge.sources": "{count} kaynak",
            "badge.high_confidence": "Yüksek veri güveni",
            "legal.privacy_title": "Gizlilik politikası",
            "legal.privacy_body": "ŞarjBul konumunu yalnızca yakındaki istasyonları bulmak ve rota hesaplamak için kullanır; konum hesabına kaydedilmez. E-posta adresin giriş, favori senkronizasyonu ve durum bildirimi için Firebase üzerinden işlenir. Crashlytics teknik çökme verilerini uygulama kararlılığı için kullanabilir. App Check yetkisiz backend erişimini azaltır. Veriler reklam veya takip amacıyla kullanılmaz. Hesabını ve ilişkili verilerini Hesap ekranından silebilirsin.",
            "legal.terms_title": "Kullanım koşulları",
            "legal.terms_body": "İstasyon, fiyat, uygunluk, menzil ve rota bilgileri karar desteği sağlar; gerçek yol ve operatör verileri değişebilir. Sürüş sırasında cihazı kullanma. Yola çıkmadan önce aracının menzilini, yol koşullarını ve istasyonun operatör bilgilerini doğrula.",
            "legal.support_title": "Destek",
            "legal.support_body": "Bir veri hatası, hesap sorunu veya erişilebilirlik problemi bildirirken istasyon adını ve yaşadığın adımları ekle.",
            "legal.open_web": "Web sayfasını aç",
            "legal.email": "E-posta gönder"
        ],
        .en: [
            "status.ok": "Done",
            "status.error": "Error",
            "network.offline": "You're offline · saved station data is in use",
            "data.loading": "Preparing stations",
            "data.refresh": "Try again",
            "data.ready": "{count} stations ready",
            "data.updated": "{count} stations updated",
            "auth.hero_line1": "Catch",
            "auth.hero_line2": "the charge.",
            "auth.card_title": "Continue with your account",
            "auth.card_hint": "Favorites and reports are saved to your account.",
            "auth.login": "Sign in",
            "auth.register": "Register",
            "auth.reset": "Reset",
            "auth.mode_label": "Account action",
            "auth.continue": "Continue",
            "auth.email": "Email",
            "auth.email_placeholder": "you@example.com",
            "auth.password": "Password",
            "auth.password_placeholder": "Your password",
            "auth.login_action": "Sign in",
            "auth.register_action": "Create account",
            "auth.reset_action": "Send reset link",
            "auth.login_loading": "Signing in...",
            "auth.register_loading": "Creating account...",
            "auth.reset_loading": "Preparing link...",
            "auth.forgot_password": "Forgot password",
            "auth.back_to_login": "Back to sign in",
            "auth.reset_hint": "Enter your email and we will send a reset link.",
            "auth.reset_email_required": "Enter your email to reset your password.",
            "auth.fill_fields": "Enter your email and password.",
            "auth.guest_primary_title": "Find a charger right away",
            "auth.guest_primary_hint": "No membership required. Choose your location and build your route.",
            "auth.guest_primary_action": "Start now",
            "auth.verified_driver": "Verified driver",
            "auth.signed_in_hint": "Favorites and status reports sync with this account.",
            "auth.logout": "Sign out",
            "auth.delete_account": "Delete account",
            "auth.delete_title": "Permanently delete your account?",
            "auth.delete_message": "Deletion starts for your account, favorites, and associated data. This action cannot be undone.",
            "auth.delete_confirm": "Delete permanently",
            "auth.delete_cancel": "Cancel",
            "auth.delete_loading": "Deleting account...",
            "auth.privacy": "Privacy",
            "auth.terms": "Terms of use",
            "auth.support": "Support",
            "auth.about": "About the app",
            "auth.version": "Version {version}",
            "auth.firebase_config_required": "Add AppConfig.plist to enable Firebase.",
            "bottom.home": "Home",
            "bottom.map": "Lounge",
            "bottom.routes": "Routes",
            "bottom.account": "Account",
            "navigation.open": "Open navigation menu",
            "nav.back": "Back",
            "home.quick_near": "Nearest",
            "home.quick_fast": "Fast",
            "home.quick_value": "Value",
            "home.search_title": "Where are you starting?",
            "home.location_selected": "No location selected",
            "home.use_location": "Use my location",
            "home.location_waiting_authorized": "Getting location. City or coordinate entry opens if no signal arrives.",
            "home.location_waiting_pending": "Waiting for location permission. City or coordinate entry opens if you decline.",
            "home.location_waiting_failed": "Location is unavailable. Continue with a city or coordinates.",
            "home.location_pick": "Choose a city or area",
            "home.latitude": "Latitude",
            "home.longitude": "Longitude",
            "home.use_manual_location": "Use manual location",
            "home.open_settings": "Open Settings for location access",
            "place.my_location": "My location",
            "place.choose_origin": "Choose start",
            "place.choose_destination": "Add destination",
            "place.not_selected": "Not selected",
            "place.optional": "Optional",
            "place.clear_destination": "Remove destination",
            "place.origin_title": "Starting point",
            "place.destination_title": "Where are you going?",
            "place.origin_hint": "Search for an address, area, or place",
            "place.destination_hint": "Search your destination to find chargers along the route",
            "place.search_prompt": "Search address or place",
            "catalog.kicker": "Driving profile",
            "catalog.charge_percent": "Charge %",
            "catalog.capacity": "Battery capacity",
            "catalog.consumption": "Average consumption",
            "charge.low": "Low",
            "charge.ready": "Ready to drive",
            "charge.long_range": "Long range",
            "charge.label": "Charge",
            "charge.selected_level": "Selected battery level",
            "filters.title": "Filters and driving settings",
            "filters.preference": "Preference",
            "filters.power": "Power",
            "filters.minimum_power": "Minimum {power} kW",
            "filters.socket": "Socket",
            "filters.range": "Hide out-of-range",
            "filters.apply": "Apply",
            "home.insight_kicker": "Smart range suggestion",
            "home.insight_title": "Ready to go with {range} km of safe range",
            "summary.safe_range_value": "%{percent} · {range} km safe range",
            "location.find_charger": "Find the Best Station",
            "location.calculating": "Calculating...",
            "service.firebase_missing": "Firebase settings are not defined in AppConfig.plist.",
            "service.reset_sent": "Password reset link sent.",
            "service.verification_sent": "Account created. A verification link was sent by email.",
            "service.verification_pending": "Account created, but the verification email could not be sent. Try again later.",
            "service.account_deleted": "Account deleted.",
            "service.favorite_login_required": "Sign in to save this station.",
            "service.report_login_required": "Sign in to report station status.",
            "service.no_session": "No session.",
            "service.invalid_credentials": "The email or password is incorrect.",
            "service.email_exists": "An account already exists for this email.",
            "service.weak_password": "The password must contain at least 6 characters.",
            "service.too_many_attempts": "Too many attempts. Wait a moment and try again.",
            "service.network_error": "Could not connect. Check your connection and try again.",
            "service.report_sent": "Your station report was received.",
            "service.report_cooldown": "Wait {seconds} seconds before sending another report.",
            "deep_link.not_found": "This charging point is not in the current data set.",
            "deep_link.location_needed": "Choose your location before opening this charging point.",
            "route.location_required": "Choose a location for the route.",
            "route.idle": "Route is not ready",
            "route.idle_hint": "Choose your location on Home and tap Find the Best Station.",
            "route.searching": "Calculating the best stops",
            "route.failed": "Route could not be calculated",
            "route.empty": "No suitable station found",
            "route.empty_hint": "Try relaxing the filters.",
            "route.back_home": "Back to Home",
            "feed.score": "SCORE",
            "feed.route_approximate": "APPROXIMATE ROUTE",
            "feed.route_live": "LIVE ROUTE",
            "feed.expand_map": "Expand map",
            "feed.view_mode": "View",
            "feed.cards": "Cards",
            "feed.map": "Map",
            "feed.filters": "Open filters",
            "map.current_location": "Current location",
            "map.open_detail": "Open station details",
            "feed.minute": "min",
            "feed.arrival": "arrival",
            "feed.arrival_charge": "Arrival charge",
            "feed.deviation": "Deviation",
            "feed.power": "POWER",
            "feed.socket": "SOCKET",
            "feed.price": "PRICE",
            "feed.detail_card": "CHARGING POINT",
            "feed.open_route": "Open Route",
            "feed.apple_maps": "Apple Maps",
            "feed.google_maps": "Google Maps",
            "feed.apple_maps_short": "Apple",
            "feed.google_maps_short": "Google",
            "feed.open_in_maps": "Open route in Maps",
            "feed.favorite_add": "Add to favorites",
            "feed.favorite_remove": "Remove from favorites",
            "feed.share": "Share charging point",
            "actions.available": "Available",
            "actions.issue_value": "Issue",
            "actions.queue_value": "Queue",
            "lounge.kicker": "Charging break",
            "lounge.title": "Lounge",
            "lounge.subtitle": "A short, surprising reflex game while your vehicle charges.",
            "lounge.game_title": "VOLT DASH",
            "lounge.best": "BEST",
            "lounge.score": "SCORE",
            "lounge.start": "Start",
            "lounge.jump": "Jump",
            "lounge.ready": "Ready",
            "lounge.running": "Running",
            "lounge.crashed": "Crashed",
            "reminder.title": "Charging reminder",
            "reminder.hint": "Set a local reminder so you do not forget to check your vehicle.",
            "reminder.minutes": "{minutes} min",
            "reminder.set": "Remind me",
            "reminder.cancel": "Cancel",
            "reminder.scheduled": "Ready for {minutes} minutes from now.",
            "reminder.cancelled": "Reminder cancelled.",
            "reminder.denied": "Notifications are disabled. You can enable them in Settings.",
            "reminder.notification_title": "Check your charge",
            "reminder.notification_body": "It is time to check your vehicle's charging status.",
            "library.favorites": "Favorites",
            "library.recent": "Recent routes",
            "library.empty_favorites": "You have no favorite stations yet.",
            "library.open_route": "Open route",
            "intent.balanced": "Balanced",
            "intent.near": "Nearest",
            "intent.fast": "Fast",
            "intent.economic": "Value",
            "badge.risk": "Risk reported",
            "badge.last_positive": "Last report positive",
            "badge.no_live": "No live data",
            "badge.arrival_safe": "Arrival safe",
            "badge.arrival_low": "Arrival low",
            "badge.fast_dc": "Fast DC",
            "badge.dc": "DC",
            "badge.sources": "{count} sources",
            "badge.high_confidence": "High data confidence",
            "legal.privacy_title": "Privacy policy",
            "legal.privacy_body": "SarjBul uses your location only to find nearby stations and calculate routes; it is not stored with your account. Your email is processed through Firebase for sign-in, favorite sync, and station reports. Crashlytics may process technical crash data for stability, while App Check reduces unauthorized backend access. Data is not used for advertising or tracking. You can delete your account and associated data from the Account screen.",
            "legal.terms_title": "Terms of use",
            "legal.terms_body": "Station, price, availability, range, and route information is decision support and may differ from current road or operator data. Do not operate the device while driving. Verify your vehicle range, road conditions, and operator information before departure.",
            "legal.support_title": "Support",
            "legal.support_body": "When reporting a data, account, or accessibility issue, include the station name and the steps that led to the problem.",
            "legal.open_web": "Open web page",
            "legal.email": "Send email"
        ]
    ]
}
