#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "SarjBul" / "Resources" / "design-tokens.json"
APP_OUTPUT = ROOT / "SarjBul" / "Generated" / "DesignTokens.generated.swift"
WIDGET_OUTPUT = ROOT / "SarjBulWidgets" / "Generated" / "DesignTokens.generated.swift"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def camel_case(value: str) -> str:
    pieces = value.replace("-", "_").split("_")
    return pieces[0] + "".join(piece[:1].upper() + piece[1:] for piece in pieces[1:])


def generate(tokens: dict) -> str:
    lines = [
        "// Generated by Scripts/generate_design_tokens.py. Do not edit.",
        "import Foundation",
        "",
        "struct SBGeneratedColorToken {",
        "    let hex: String",
        "    let opacity: Double",
        "}",
        "",
        "struct SBGeneratedShadowToken {",
        "    let color: String",
        "    let opacity: Double",
        "    let radius: Double",
        "    let x: Double",
        "    let y: Double",
        "}",
        "",
        "enum SBGeneratedTokens {",
        f"    static let source = {swift_string(tokens['source'])}",
        "",
    ]

    for name, token in tokens["colors"].items():
        lines.append(
            f"    static let {camel_case(name)} = SBGeneratedColorToken("
            f"hex: {swift_string(token['hex'])}, opacity: {float(token['opacity'])})"
        )

    lines.append("")
    for name, value in tokens["radius"].items():
        lines.append(f"    static let radius{camel_case(name).capitalize()} = {float(value)}")

    lines.append("")
    for name, token in tokens["shadows"].items():
        lines.append(
            f"    static let shadow{camel_case(name).capitalize()} = SBGeneratedShadowToken("
            f"color: {swift_string(token['color'])}, opacity: {float(token['opacity'])}, "
            f"radius: {float(token['radius'])}, x: {float(token['x'])}, y: {float(token['y'])})"
        )

    fonts = tokens["fonts"]
    lines.extend([
        "",
        f"    static let displayFont = {swift_string(fonts['display'])}",
        f"    static let bodyFont = {swift_string(fonts['body'])}",
        f"    static let iosDisplayDesign = {swift_string(fonts['iosDisplayDesign'])}",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    tokens = json.loads(SOURCE.read_text(encoding="utf-8"))
    requested_output = parse_args().output
    outputs = [requested_output] if requested_output else [APP_OUTPUT, WIDGET_OUTPUT]
    generated = generate(tokens)
    for output in outputs:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
